nginx-acme:
  build: guac-nginx/.  
  ports:
    - 80:80
    - 443:443
  links:
    - guacamole 
  environment:
    - "DOMAINS=mischief.squeakcloud.com -> http://guacamole:8080"
    - "PRODUCTION=true"
    - "FORCE_RENEW=false"
squeak5:
  container_name: squeak5
  image: pshouse/vnc-squeak:0.8
  expose:
   - "5900"
postgres:
  build: guac-postgres/.
  container_name: postgres
  environment:
   - POTSGRES_PASSWORD=guac
guacd:
  container_name: guacd
  image: glyptodon/guacd
  links:
   - squeak5
guacamole:
  container_name: guacamole
  image: glyptodon/guacamole
  links: 
   - guacd:guacd
   - postgres:postgres
   - squeak5:squeak5
  environment:
   - POSTGRES_DATABASE=guacamole_db
   - POSTGRES_USER=postgres 
   - POSTGRES_PASSWORD=guac
  ports:
   - "8080:8080"
