apiVersion: v1
kind: Pod
metadata:
  name: postgtres
  labels:
    name: postgres
spec:
  containers:
    - resources:
        limits:
          cpu: 0.5
      image: pshouse/guac-postgres
      name: postgres
      env:
        - POTSGRES_PASSWORD: guac
      ports:
